# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ptsrv',
                'doc_host': 'https://owen-AR.github.io',
                'git_url': 'https://github.com/owen-AR/ptsrv',
                'lib_path': 'ptsrv'},
  'syms': {'ptsrv.core': {'ptsrv.core.foo': ('core.html#foo', 'ptsrv/core.py')}}}
